steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --no-push
      - --cache-repo=europe-west2-docker.pkg.dev/$PROJECT_ID/demo/${_REPO_NAME}/cache
      - --dockerfile=Dockerfile
      - --cache=true
      - --cache-ttl=168h

options:
  machineType: 'E2_HIGHCPU_8'
