steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=europe-west2-docker.pkg.dev/$PROJECT_ID/demo/${_REPO_NAME}:${_COMMIT_SHA}
      - --destination=europe-west2-docker.pkg.dev/$PROJECT_ID/demo/${_REPO_NAME}
      - --dockerfile=Dockerfile
      - --cache=true
      - --cache-ttl=168h
